apiVersion: cluster.appdynamics.com/v1alpha1
kind: OTelCollector
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-otel-collector" | trunc 63 }}
spec:
  {{- template "podConfigs" .Values.otelCollectorPod }}

  serviceAccountName: {{ .Values.otelCollectorServiceAccount}}

  {{ with .Values.mTLS -}}
  mTLS:
    enabled: {{ .enabled | quote }}
    {{ if .enabled -}}
    secretName: {{ required "A valid secret name entry required!" .server.secretName }}
    secretKeys:
      caCert: {{ .server.secretKeys.caCert }}
      tlsCert: {{ .server.secretKeys.tlsCert }}
      tlsKey: {{ .server.secretKeys.tlsKey }}
    {{- end }}
  {{- end }}

  {{ if .Values.otelCollector.apmNamespaces -}}
  apmNamespaces: {{ .Values.otelCollector.apmNamespaces }}
  {{- end}}

  env:
  {{- toYaml .Values.otelCollectorPod.env | nindent 4 }}

  {{ if .Values.otelCollector.configOverride -}}
  configOverride: |
  {{ .Values.otelCollector.configOverride | nindent 6 }}

  {{ else -}}
  {{ with .Values.otelCollector.config -}}
  config:
    oauth2client:
      clientId: {{ required "A valid otelCollector.config.oauth2client.clientId entry required!" .oauth2client.clientId }}
      tenantId: {{ required "A valid otelCollector.config.oauth2client.tenantId entry required!" .oauth2client.tenantId }}
    endpoint: {{ required "A valid otelCollector.config.endpoint entry required!" .endpoint }}
    logLevel: {{ .logLevel }}
  {{- end }}

  {{- end }}
