apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appdynamics-operator-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - create
  - update
  - list
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - create
  - update
  - list
  - watch
