operatorServiceAccount: appdynamics-operator
operatorPod:
  image: public.ecr.aws/appdynamics-container-registry/appdynamics-operator:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}
