apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hostcollectors.appdynamics.com
spec:
  group: appdynamics.com
  names:
    kind: Hostcollector
    listKind: HostcollectorList
    plural: hostcollectors
    singular: hostcollector
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
