apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdynamics-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appdynamics-operator
  template:
    metadata:
      labels:
        name: appdynamics-operator
    spec:
      serviceAccountName: {{ .Values.operatorServiceAccount }}
      tolerations:
      {{- toYaml .Values.operatorPod.tolerations | nindent 8 }}
      {{ if .Values.operatorPod.imagePullSecret -}}
      imagePullSecrets:
        - name: {{ .Values.operatorPod.imagePullSecret }}
      {{ end -}}
      {{ if .Values.operatorPod.priorityClassName -}}
      priorityClassName: {{ .Values.operatorPod.priorityClassName }}
      {{ end -}}
      nodeSelector:
      {{- toYaml .Values.operatorPod.nodeSelector | nindent 8 }}
      containers:
        - name: appdynamics-operator
          image: {{ .Values.imageInfo.operatorImage }}:{{ .Values.imageInfo.operatorTag }}
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - appdynamics-operator
          imagePullPolicy: {{ .Values.imageInfo.imagePullPolicy }}
          resources:
          {{- toYaml .Values.operatorPod.resources | nindent 12 }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "appdynamics-operator"

