{{ if not .Values.crbStage -}}
{{- if .Values.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operatorServiceAccount }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{ end -}}
