{{ $namespace := .Release.Namespace }}
{{ with .Values -}}
{{ $mode := .deploymentMode -}}
{{ if or (eq $mode "MASTER") (eq $mode "NAMESPACED") -}}
{{ if .controllerInfo.customSSLCert -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-ssl-cert
  namespace: {{ $namespace }}
type: Opaque
data:
  "custom-ssl.pem": {{ .controllerInfo.customSSLCert }} 
{{ end -}}
{{ end -}}
{{ end -}}
