{{ $namespace := .Release.Namespace }}
{{ with .Values -}}
{{ $mode := .deploymentMode -}}
{{ if or (eq $mode "MASTER") (eq $mode "NAMESPACED") -}}
{{ if .controllerInfo.authenticateProxy -}}
{{ if not .controllerInfo.proxyUrl -}}
{{ fail "Proxy url is requried to authenticate proxy!" -}}
{{ end -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-proxy-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  proxy-password: {{ include "sensitiveData" (dict "data" .controllerInfo.proxyPassword "message" "Proxy password is required!") }}
{{ end -}}
{{ end -}}
{{ end -}}
